# Generated by Django 5.0.7 on 2024-07-22 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sales', '0003_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.category'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product'),
        ),
    ]
